### ISSUE TITLE
Adding a syntax definition for variable names when assigned to a JS arrow function

### ISSUE THREAD

**Issue by ericbiewener** [borela/naomi#10]
Given the following code:

```javascript
const doSomething = () => ...;
const doSomethingElse = arg => {
  ...
};

const justAvariable = 1;
```

I'd love to be able to color `doSomething` and `doSomethingElse` differently from `justAvariable` since they are functions.

Great work on this package!

**Comment by borela** [comment]
Hi Eric, nice catch, 
This was actually a bug as they should be colored as function, I did some changes and sent the commits, it should highlight both `doSomething` and `doSomethingElse` as functions. Can you check if it is working now?
Thank you

**Comment by borela** [comment]
This is the result (color scheme Candyman) using the latest commits:

![captura de tela 2017-04-27 16 18 04](https://cloud.githubusercontent.com/assets/11317458/25500367/2d13498e-2b65-11e7-9348-01b435d02e51.png)

Can you confirm if its working in your code too?

**Comment by borela** [comment]
Confirmed, it's fixed.
