### ISSUE TITLE
[Styled Components] Support line comments

### ISSUE THREAD

**Issue by 2Pacalypse-** [borela/naomi#100]
Currently, writing block comments inside a styled component works fine:

![block](https://user-images.githubusercontent.com/4757944/37555534-d82ee77e-29e8-11e8-9878-937716076d67.png)

But writing line comments doesn't work as fine:

![line](https://user-images.githubusercontent.com/4757944/37555537-ea54f97a-29e8-11e8-9525-b2c93dec9b4c.png)

Since styled-components [support line comments](https://github.com/styled-components/stylelint-processor-styled-components/pull/164) now, it would be nice to support it here as well.

**Comment by borela** [comment]
Nice to know they are supporting it, I wish CSS supported it too, released the patch https://github.com/borela/naomi/releases/tag/v3.13.0
