### ISSUE TITLE
[Styled Components] Support API helpers & Nesting

### ISSUE THREAD

**Issue by 2Pacalypse-** [borela/naomi#101]
Currently, styled components [API helpers](https://www.styled-components.com/docs/api#helpers) are not supported, which results in formatting like this:

![helpers](https://user-images.githubusercontent.com/4757944/37556429-27da919e-29f6-11e8-89f8-51e11bd44203.png)

It would be nice if they're supported as well. Thanks!

**Comment by borela** [comment]
From the page you linked I can see styled components supports nesting too, I'll add that feature also.

**Comment by 2Pacalypse-** [comment]
Awesome!

I'm sorry to swamp you with all these `styled-components` requests, but could you also add support for [`withComponent`](https://www.styled-components.com/docs/api#withcomponent) 😄? Currently it looks like this:

![withcomponent](https://user-images.githubusercontent.com/4757944/37557062-2517662c-29ff-11e8-85e9-606aa842aa12.png)

**Comment by borela** [comment]
That's actually a bug, it should've been highlighting the styled component, nice catch :D

**Comment by borela** [comment]
Added in https://github.com/borela/naomi/releases/tag/v3.14.0
