### ISSUE TITLE
Comments misbehaving in normal javascript objects

### ISSUE THREAD

**Issue by franciscolourenco** [borela/naomi#102]
- Can't uncomment inside javascript objects.
- Trying to write a comment in an empty line comments above and bellow line too.

![naomi comments](https://user-images.githubusercontent.com/208149/37568173-e35e14e6-2ad1-11e8-8259-a21829ad17be.gif)

```js
const example = {
  hello: 'world',
  foo: 'bar'
}
```

Naomi 3.13.0
Sublime 3143

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v3.14.0
