### ISSUE TITLE
css grid syntax not parsed correctly 

### ISSUE THREAD

**Issue by tjimsk** [borela/naomi#103]
Given the following styled-component declaration:

    const Container = styled.div`
	display: grid;

	grid-template-rows: 
		[top-panel-start top-panel-end] 32px
		[bottom-panel-start view-end];
	grid-template-columns: 
		[view-start view-end] 1fr;
	grid-gap: 1px;
`

The output looks like the following:

![screen shot 2018-03-20 at 2 15 01 am](https://user-images.githubusercontent.com/10207473/37614047-9550078c-2be4-11e8-8d67-aec92a570b14.png)

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v3.14.0
