### ISSUE TITLE
Comments don't behave as expected

### ISSUE THREAD

**Issue by Whoaa512** [borela/naomi#105]
Here's a screencast: https://drive.google.com/file/d/1arcw1SX9qZhLT9dWwZF7nX-1st_qIDs-/view

In that I'm starting with Naomi enabled and try to use the shortcuts for comment/uncomment. Then I disable Naomi and use what I assume to be either the default comment functionality or the one provided by the babel-sublime plugin.

In any case, I'd like to option to have all my commented lines start at the same indentation like babel-sublime.

**Comment by borela** [comment]
I am rewriting the comment toggle plugin to simplify its logic(JSX blocks makes the detection a lot harder) and I should have a patch this week. The behavior you want should actually be the default.

**Comment by Whoaa512** [comment]
Awesome thanks for the update.

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v3.14.0
