### ISSUE TITLE
JS class with lowercase name problem

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#107]
Broken
<img width="548" alt="screen shot 2018-03-22 at 3 16 39 pm" src="https://user-images.githubusercontent.com/1213198/37772676-0851d318-2de4-11e8-901b-0325097c99eb.png">
Ok
<img width="584" alt="screen shot 2018-03-22 at 3 17 08 pm" src="https://user-images.githubusercontent.com/1213198/37772695-18e93afe-2de4-11e8-9e07-3a754f4e116b.png">

**Comment by borela** [comment]
https://github.com/borela/naomi/releases/tag/v3.14.1
