### ISSUE TITLE
Jest snapshot syntax problem

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#108]
Only first exports looks good
<img width="871" alt="screen shot 2018-03-22 at 3 18 03 pm" src="https://user-images.githubusercontent.com/1213198/37772737-3fdf4432-2de4-11e8-926e-010d36f2f387.png">

**Comment by borela** [comment]
The current syntax is trying to highlight enzyme snapshots:
```
exports[`test should render a label 1`] = `
<label
  className="isBlock">
  Hello Jest!
</label>
`;

exports[`test should render a small label 1`] = `
<label
  className="isBlock isSmall">
  Hello Jest!
</label>
`;
```
I believe it's possible to expand the syntax to support the other format too.

**Comment by max-mykhailenko** [comment]
Hm, looks like they are equal

**Comment by borela** [comment]
They are pretty similar, I am adding the `Object {` syntax.

**Comment by max-mykhailenko** [comment]
Object can be showed as string. It's ok. Main problem for me it's a `exports` keyword

**Comment by borela** [comment]
I expanded the syntax to cover the object syntax as this will definitely be useful to me too:

![image](https://user-images.githubusercontent.com/11317458/37779216-a21dbabc-2dca-11e8-894f-48f081b2cb9b.png)

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v3.14.2
