### ISSUE TITLE
JS typeof with next equal sign broken

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#109]
Broken
<img width="415" alt="screen shot 2018-03-22 at 3 19 21 pm" src="https://user-images.githubusercontent.com/1213198/37772811-75722d12-2de4-11e8-916d-02644ce79675.png">
Earlier additional braces fix that, but now completely broke
<img width="380" alt="screen shot 2018-03-22 at 3 22 50 pm" src="https://user-images.githubusercontent.com/1213198/37772957-f5418c7c-2de4-11e8-8279-b63c35e496c6.png">

**Comment by borela** [comment]
I tried on my machine but I wasn't able to reproduce it, please post the context where the issue happens.

**Comment by max-mykhailenko** [comment]
```export default function getGeneratorMiddleware() {
  return (store: Store<ReduxState, Action>) => (next: Function) => (action: genAction): mixed => {
    if (typeof action.next === 'function') {
      return goOn(store, action);
    }

    return next(action);
  };
}
```

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.14.1
