### ISSUE TITLE
ES16 function argument array destructuring syntax doesn't exist

### ISSUE THREAD

**Issue by ericbiewener** [borela/naomi#11]
Object destructuring in the function definition works, but not array destructuring:

![image](https://cloud.githubusercontent.com/assets/253298/24591423/bf3d2df2-17b5-11e7-8e27-cb9938d9e528.png)

**Comment by borela** [comment]
Which color scheme are you using?

**Comment by borela** [comment]
I cleaned the scopes for destructuring and added specific ones when in function parameters in this [commit](https://github.com/borela/naomi/commit/117b3bd427e38ea170a4a37c43246323e08c1e66). The result using the current candyman color scheme is as follows:

![destruct](https://cloud.githubusercontent.com/assets/11317458/25429194/9bb5c744-2a4e-11e7-8e62-509879252268.png)

**Comment by ericbiewener** [comment]
Looks great!
