### ISSUE TITLE
Flow. Wrong syntax highlight for object definition

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#116]
Bug looks like 
<img width="242" alt="screen shot 2018-03-27 at 5 24 42 pm" src="https://user-images.githubusercontent.com/1213198/37973822-09ebd30a-31e4-11e8-889b-9e2ace370689.png">

Code for testing

```js
// @flow

export type User = {|
  +id: number,
  +ownSizes?: {
    clothesSize?: string,
    shoesSize?: string,
  },
  +refCity?: string,
  +refPost?: string,
|};
```

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.15.4

**Comment by borela** [comment]
The patch is on package control too.
