### ISSUE TITLE
`tagsOptions: stippled_underline` not supported

### ISSUE THREAD

**Issue by ericbiewener** [borela/naomi#12]
With the babel-sublime package, it will denote the opening and closing JSX tags with a dotted underline: 

![image](https://cloud.githubusercontent.com/assets/253298/24591608/c71de2dc-17ba-11e7-961c-49682192e503.png)

This is achieved simply via `* { tagsOptions: stippled_underline }`. This appears not to be supported in Naomi.

**Comment by borela** [comment]
I sent some commits and this should be working too.

**Comment by borela** [comment]
The result (color scheme Candyman) using the latest commits:

![captura de tela 2017-04-27 16 20 28](https://cloud.githubusercontent.com/assets/11317458/25500467/7f9c6bd6-2b65-11e7-8d6b-6632571e4a21.png)

Can you confirm if it is working for your code too?

**Comment by borela** [comment]
Also, I saw you were porting a color scheme, if you need help, feel free to message me.

**Comment by borela** [comment]
Confirmed, it's fixed.
