### ISSUE TITLE
[Color scheme][JSON] Request to colorize nested objects

### ISSUE THREAD

**Issue by Whoaa512** [borela/naomi#120]
I used to use [Oceanic Next](https://github.com/voronianski/oceanic-next-color-scheme) but I'm trying to switch over to Candyman completely.

However the JSON highlighting makes my eyes hurt.

My request to is colorize the object keys for different nesting levels like so:
<img width="680" alt="screenshot 2018-03-30 12 53 55" src="https://user-images.githubusercontent.com/1581943/38151893-ef2e1072-3419-11e8-8d1d-392179a0bb64.png">

vs.

<img width="648" alt="screenshot 2018-03-30 12 57 56" src="https://user-images.githubusercontent.com/1581943/38151905-fba04c30-3419-11e8-9adb-d04fe2c78d21.png">

Sample code:
```json
{
  "dependencies": {
    "aws-sdk": "^2.45.0",
    "axios": "^0.16.1",
    "bluebird": "^3.5.0",
    "cheerio": "^0.22.0",
    "faker": "^4.1.0",
    "graphql-decorators": "^0.0.4",
    "knex": "^0.12.6",
    "mysql": "^2.13.0",
    "react": "^15.5.4",
    "react-apollo": "^1.2.0",
    "react-dom": "^15.5.4",
    "ua-parser-js": "^0.7.12",
    "useragent": "^2.1.13"
  },
  "name": "wat",
  "version": "1.0.0",
  "main": "index.js",
  "author": "C.J. Winslow <whoaa512@gmail.com> (https://github.com/whoaa512)",
  "license": "MIT"
}


```

**Comment by borela** [comment]
Which syntax are you using for JSON? Here's how it looks with the builtin JSON syntax, it already has different colors per level:

![image](https://user-images.githubusercontent.com/11317458/38154805-84d7a784-344a-11e8-97f0-1c8e23733f83.png)

**Comment by Whoaa512** [comment]
Yup working as intended. Had the default JS package disabled for some reason.
