### ISSUE TITLE
[JS/Flow] Default parameter after nullish

### ISSUE THREAD

**Issue by Whoaa512** [borela/naomi#121]
## Image
<img width="583" alt="screenshot 2018-03-30 13 26 36" src="https://user-images.githubusercontent.com/1581943/38152789-30a6420a-341e-11e8-8397-f2ae557d3233.png">

## Sample code

```javascript
// @flow

export class SmartQuery {
    __isTracked: boolean

    constructor(trackEvents?: boolean = true, work: boolean = true) {
        this.__isTracked = trackEvents
    }
}

```

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.15.6

**Comment by borela** [comment]
The patch is on package control.
