### ISSUE TITLE
[Styled Components] Multiple parenthesis in `calc` function break styling

### ISSUE THREAD

**Issue by 2Pacalypse-** [borela/naomi#123]
It works when there's only a single-level of parenthesis, but nesting them causes this:

![untitled1](https://user-images.githubusercontent.com/4757944/38172957-f932fd10-35b5-11e8-9d76-c5d42e963cf4.png)

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v4.2.1
If the patch didn't work or it still breaks in another case, feel free to reopen or post a new issue;
