### ISSUE TITLE
[Styled Components] Using `extend` after `withComponent` is not styled

### ISSUE THREAD

**Issue by 2Pacalypse-** [borela/naomi#124]
Example:

![untitled3](https://user-images.githubusercontent.com/4757944/38172974-4a1bdd50-35b6-11e8-8fe7-c42d500bfefa.png)

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v4.2.1
If the patch didn't work or it still breaks in another case, feel free to reopen or post a new issue;

**Comment by mvllow** [comment]
I was creating an issue about a similar case imaged below. I will of course test this when I get a chance but just curious if anyone knows whether the above method of extending styles is better/worse than my method below. Appreciate any input!

![Screen Shot 2019-04-11 at 10 33 09 AM](https://user-images.githubusercontent.com/1474821/55971012-4533ce80-5c46-11e9-9d3c-9941bb5bb447.png)

**Comment by 2Pacalypse-** [comment]
This is not really related to Naomi. You should take a look at the styled component docs.
For example, the `.extend` API has been deprecated: https://www.styled-components.com/docs/api#deprecated-extend
Also, `.withComponent` API is also marked for deprecation, you should use the `as` prop instead: https://www.styled-components.com/docs/api#withcomponent
