### ISSUE TITLE
PHP syntax highlighting broken by global variable variables

### ISSUE THREAD

**Issue by imjoehaines** [borela/naomi#13]
In one of the more horrendous pieces of code we have a function that uses global variable variables which breaks the syntax highlighting. After the global variable variable everything is grey:

![screen shot 2017-05-02 at 10 25 12](https://cloud.githubusercontent.com/assets/282732/25612194/a5ce3ee6-2f21-11e7-961a-7de8040486da.png)

This seems to happen a lot with other instances using variable variables too; in `if` statements, `foreach` loops etc&hellip;

For copy & pasting:

```php
<?php

$a = 1;
$b = 'a'

switch ($a) {
    case 1:
        global $$b;
        echo $$b;
        echo $$b;
        echo $$b;
        echo $$b;
}
```

**Comment by borela** [comment]
I'll try to fix it this week, the PHP syntax needs some cleaning.

**Comment by borela** [comment]
I rewrote the syntax and removed a lot of the restrictions which were causing this issue, can you take a look and see if it is working?

**Comment by imjoehaines** [comment]
Yeah, this seems to have fixed it thanks!
