### ISSUE TITLE
JS arrow function default args interfering with function body highlighting

### ISSUE THREAD

**Issue by gavinhungry** [borela/naomi#130]
I'm using Naomi 3.15.8 on Sublime Text 3 3153.

A multiline arrow function with (certain) default argument values interferes with the highlighting of the function body.

Default value is an empty array (bad):
![1](https://user-images.githubusercontent.com/744538/38884650-121b953c-4225-11e8-96a0-cb3d3022ec96.png)

Default value is an empty object (OK):
![2](https://user-images.githubusercontent.com/744538/38884663-1d510630-4225-11e8-9f0f-c850d743c7f7.png)

```js
let foo = ({
  bar = []
} = {}) => {
  console.log(bar);
};
```

This may be related to #25.

**Comment by borela** [comment]
Unfortunately it is a limitation in sublime's regex engine, everything until `=>` must be on the same line for the arrow function to be detected correctly.

**Comment by gavinhungry** [comment]
@borela,

I'm not concerned with the function name or arguments being highlighted, but rather the *body* of the function (which your comment in https://github.com/borela/naomi/issues/25#issuecomment-361060009 says was fixed). Note that the `console.log` line (the body) is highlighted correctly when the default argument value is an object (`{}`).

Here's another example, with a larger function body to illustrate what I mean:
![3](https://user-images.githubusercontent.com/744538/38889365-662bd57a-4233-11e8-89f4-3eb20d1e757f.png)

I also noted that a colon `:` in a comment after the default argument seems to fix the body, but strangely attempts to highlight the comment itself:
![1](https://user-images.githubusercontent.com/744538/38889534-d93f7d46-4233-11e8-8b13-6cbd8f8a189a.png)

When the default argument `bar` is an something other than an array, everything seems fine:
![2](https://user-images.githubusercontent.com/744538/38889596-0f9a1e5a-4234-11e8-8924-c58f712a3bd0.png)

All of the above snippets highlight correctly with the default Sublime Text JavaScript highlighting.

**Comment by borela** [comment]
Oo I get it, I'll add a fallback to it, the object literal is not recognizing its end.

**Comment by borela** [comment]
This patch https://github.com/borela/naomi/releases/tag/v3.15.9 should work
![image](https://user-images.githubusercontent.com/11317458/38898887-adf8e562-426c-11e8-8960-9d4ca794e0cf.png)

**Comment by gavinhungry** [comment]
@borela,

Thanks! I confirmed that this is working as expected with Naomi 3.15.9.
