### ISSUE TITLE
(Styled Components) Bug with template string within calc()

### ISSUE THREAD

**Issue by davidcalhoun** [borela/naomi#131]
Thanks for creating this!  This is the best syntax highlighter I've found that plays nicely with `styled-components` for the most part!

Looks like there's a bug with template strings inside `calc`:

<img width="639" alt="screen shot 2018-04-18 at 3 31 57 pm" src="https://user-images.githubusercontent.com/120596/38961544-daeda330-431d-11e8-9329-2c00d1c96c57.png">

Here's what it should look like (replaced the template var with `0`):
<img width="438" alt="screen shot 2018-04-18 at 3 35 57 pm" src="https://user-images.githubusercontent.com/120596/38961653-582056e0-431e-11e8-9262-838983c0c4f2.png">

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.15.10

**Comment by davidcalhoun** [comment]
Nice!  Thanks!

**Comment by borela** [comment]
You're welcome! Feel free to post more issues, I am implementing tests on a separate branch based on the issues posted here.
