### ISSUE TITLE
(CSS) Parsing breaks if there's no space between key/vals (e.g. 'font-size:24px')

### ISSUE THREAD

**Issue by davidcalhoun** [borela/naomi#132]
`font-size:24px;` seems to break the parsing, but is fixed when inserting a space (`font-size: 24px;`)

### Before
<img width="313" alt="screen shot 2018-04-20 at 2 15 40 pm" src="https://user-images.githubusercontent.com/120596/39074264-8eb0c7d4-44a5-11e8-9c88-62b876085905.png">

### After inserting space
<img width="347" alt="screen shot 2018-04-20 at 2 15 49 pm" src="https://user-images.githubusercontent.com/120596/39074263-8d4e1874-44a5-11e8-9671-906b7227037f.png">

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.15.11

**Comment by borela** [comment]
You are welcome :D.
