### ISSUE TITLE
Destructuring and renaming: Sublime freezing/infinite spinner

### ISSUE THREAD

**Issue by davidcalhoun** [borela/naomi#133]
There are certain circumstances which causes Sublime to freeze when using destructuring and renaming.  This is easily reproducible and doesn't happen when switching to other syntax highlighters.

```
    foo() {
    	
    }

    baz (bar) {

    }
```

After copying the above code, try to manually type the following code into `foo()` (copying and pasting seems to have no effect)
```js
const { a: b } = {};
```

Note that the syntax highlighting causes the editor to freeze up with a spinner.  I tried to capture this below:

![kapture 2018-04-30 at 18 28 50](https://user-images.githubusercontent.com/120596/39457698-963a784a-4ca4-11e8-8b99-680cdb5d79d9.gif)

**Comment by borela** [comment]
I pushed a patch to fix this https://github.com/borela/naomi/releases/tag/v3.15.12

**Comment by borela** [comment]
@davidcalhoun After the patch gets applied, can you confirm if it is working for you?

**Comment by davidcalhoun** [comment]
Thanks again for the quick work!  Looks to be fixed now.  :)

**Comment by borela** [comment]
You are welcome :D Closing as the patch is on packagecontrol.
