### ISSUE TITLE
Color Helper isn't Working on SASS / CSS Syntax.

### ISSUE THREAD

**Issue by sajmonella9** [borela/naomi#136]
Hi, i try using Color Helper, a package to pick / highlight color on SASS / SCSS syntax. But this only works 
on .CSS File. 

What don't working? Only Color Square Near Color Name. Will be nice to support SCSS/SASS filetype.

**Comment by sajmonella9** [comment]
Edit: Sorry that was ColorHelper issue . It's are ready fixed. Problem solved.

**Comment by borela** [comment]
No problem :D
