### ISSUE TITLE
[Flow] Missing support for existential types 

### ISSUE THREAD

**Issue by ml9951** [borela/naomi#14]
The syntax highlighting fails to properly highlight code containing [existential types](https://flow.org/en/docs/types/utilities/#the-existential-type--a-classtoc-idtoc-the-existential-type-hreftoc-the-existential-typea).  

![Imgur](http://i.imgur.com/8g4esLP.png)

![Imgur](http://i.imgur.com/s5s1Iwo.png)

**Comment by borela** [comment]
Added support in this [commit](https://github.com/borela/naomi/commit/db1134a7dc7ffb9ee8754dfecd08494bb0f01414).

**Comment by ml9951** [comment]
Perfect, thanks for the quick response.
