### ISSUE TITLE
[Styled Components] Attribute selector (e.g. &[data-attribute]) breaks styling

### ISSUE THREAD

**Issue by davidcalhoun** [borela/naomi#140]
### Description
<img width="223" alt="screen shot 2018-05-25 at 12 01 31 pm" src="https://user-images.githubusercontent.com/120596/40561857-a0383742-6013-11e8-8ae1-8161b6f372e3.png">

### Code sample
```js
const Foo = styled.div`
    color: white;

    &[foo] {

    }

    background-color: black;
`;
```

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v4.2.1
If the patch didn't work or it still breaks in another case, feel free to reopen or post a new issue;
