### ISSUE TITLE
Javascript styles with Emotion styled components

### ISSUE THREAD

**Issue by jsonmaur** [borela/naomi#141]
When using Javascript object styles with [Emotion styled components](https://emotion.sh/docs/styled), it doesn't highlight correctly. Switching from `styled('div')()` to `styled.div()` seems to fix it, but Naomi should support both options (since Emotion requires a babel plugin for the latter.) Really great plugin by the way! 👍 

![screen shot 2018-05-30 at 3 13 22 pm](https://user-images.githubusercontent.com/911274/40742318-1fa8c116-641c-11e8-8631-3c21613deab9.png)

![screen shot 2018-05-30 at 3 14 34 pm](https://user-images.githubusercontent.com/911274/40742356-44df1098-641c-11e8-8243-5bfd0a85a7db.png)

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v4.2.1
If the patch didn't work or it still breaks in another case, feel free to reopen or post a new issue;
