### ISSUE TITLE
Syntax highlighting for comments in do-while

### ISSUE THREAD

**Issue by faiwer** [borela/naomi#142]
Hi. This is a small bug here:
```js
do {} 
// comment
while(false)
```
![img_05_06_01_30ae9f4808d](https://user-images.githubusercontent.com/744114/40959009-25dc4760-68bd-11e8-83b1-be0514c5aa74.png)

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.15.15 :D
