### ISSUE TITLE
Syntax highlighting in classes and window object

### ISSUE THREAD

**Issue by faiwer** [borela/naomi#144]
Hello, it's again me :)

```js
class A
{
	a = window.a && (a =>
	{
		a;
		this.a.a(a);
	});
}
```
![img_14_06_01_fb9f294b2dd](https://user-images.githubusercontent.com/744114/41401982-fce26448-6fe2-11e8-9411-f3f0c012f26e.png)

A real code is a bit tricky, so I shortened it to this ^.

**Comment by borela** [comment]
Nice find, this one was indeed a bit tricky to isolate. Fixed https://github.com/borela/naomi/releases/tag/v3.16.0
