### ISSUE TITLE
Missing support for export default

### ISSUE THREAD

**Issue by ml9951** [borela/naomi#15]
Missing support for `export default`

![Imgur](http://i.imgur.com/QAue1II.png)

**Comment by borela** [comment]
Sent a [fix](https://github.com/borela/naomi/commit/d96f209e48f9aa8c790a4429da5d11e3afe61dc9), this was because I removed some of the constraints that the released version had and forgot to fix the priority.

**Comment by ml9951** [comment]
Great, thanks!
