### ISSUE TITLE
Syntax highlighting: keyword "set"

### ISSUE THREAD

**Issue by faiwer** [borela/naomi#150]
Hello, it's again me :)

```js
const traitsMap =
{
	types:
	{
		table,
		image,
		video,
		plot,
		tableCell: table,
		tableRow: table,
		model,
		set,
		setItem,
	},
	exp:
	{
		input,
		math,
		choice,
		longMath,
		dragnest: dnd,
		dragitem: dnd,
	},
};
```
![img_26_06_01_814e9450d4b](https://user-images.githubusercontent.com/744114/41904135-7095c428-7959-11e8-808d-3977a9db9fa9.png)

The same situation with "get" keyword.

**Comment by faiwer** [comment]
Hello. In static fields is the same situation :)

```js
class A
{
	static set = 'S';
	static get = 'G';
	static anything = 'A';
}
```

![img_29_06_01_68c31ce8acf](https://user-images.githubusercontent.com/744114/42088956-3e4680d2-7bbd-11e8-952f-e545c77a5a29.png)

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.17.2
