### ISSUE TITLE
Sytax issue with React.Element FlowType

### ISSUE THREAD

**Issue by biw** [borela/naomi#152]
Describe the issue here.
Hello, I am having issues when using `React.Element` & other types with a `.` (period) in them as a return type when having more than one (`>1`) function input.
```
const tester = (var1: Function, var2: Function): React.Element<any> => var1() + var2();
tester();
```
![image](https://user-images.githubusercontent.com/6139501/42117858-2328e8a2-7bb4-11e8-89f0-9ce7600b85f5.png)

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.17.2
