### ISSUE TITLE
[JS] throw broke function

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#153]
If I add throw in function I got gray syntax after line with throw 

```js
function getUsers() {
  try {
    throw new Error('123');
  } catch (e) {
    log.error(e);
  }
}
```
![image](https://user-images.githubusercontent.com/1213198/42126711-b1185cac-7c94-11e8-9df7-93277227820e.png)

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v4.0.0

**Comment by monopixmonopix** [comment]
#metoo
It's not about 'throw' just about 'new'

**Comment by StreetStrider** [comment]
Good catch :+1: I've faced this issue in recent 24hrs too. Awesome fast fixing!

**Comment by borela** [comment]
This can be closed, I can confirm that it is fixed in the latest version.
