### ISSUE TITLE
Syntax highlighting: RegExp

### ISSUE THREAD

**Issue by faiwer** [borela/naomi#154]
Hello, it's again me. This is a strange one :)
```js
export const a = a =>
{
	return a
		.a(/<\/x>(\s*)<x>/)
		// [b]b[/b] => <b>b</b>
};
export const a = () => {};
```
![img_03_07_01_00f913f3505](https://user-images.githubusercontent.com/744114/42209358-4337890e-7ed0-11e8-9941-31787e703834.png)

There are 2 troubles: 
- the second `export const` is white instead of red-blue
- the line with comment (if you cut it to `// [b]b[/b] => `) breaks everything:

![img_03_07_01_cd2b1a6f516](https://user-images.githubusercontent.com/744114/42209462-7edd24f0-7ed0-11e8-86be-74cebb1d0fca.png)

Is it okay that I create so much syntax-highlighting issues for you? :)

**Comment by borela** [comment]
Nice find, this edge case was caused by the regex literal. Fixed https://github.com/borela/naomi/releases/tag/v4.0.2

**Comment by borela** [comment]
https://github.com/borela/naomi/releases/tag/v4.0.3 I reduced the flexibility of the code to either allow comments between function calls and parentheses or generics, this is not perfect but will highlight correctly most sources.
