### ISSUE TITLE
Weird issues with parenthesis and division

### ISSUE THREAD

**Issue by EmmaSimon** [borela/naomi#156]
When you have parenthesis wrapping statements that are being divided by each other, weird things start to happen.

<img width="252" alt="screen shot 2018-07-05 at 6 15 36 pm" src="https://user-images.githubusercontent.com/12971446/42350674-7912caa6-807f-11e8-8d4b-53956842786c.png">

Issues start to happen on line 2, where `a` should be white, but is instead blue. This seems to happen any time a variable (any `[a-zA-Z]`) shows up followed by `/()` with anything inside the parenthesis.

It gets even weirder on line 4, when you also wrap the variable in parenthesis. Anything can be inside these parenthesis, as long as the first group includes at least one `[a-zA-Z]` character. This changes the color of `let`, and any variables, to white.

Then whenever you have a line that includes `/()` again, `let`/`const`/`var` and any variables will turn blue, at least until the `/(`. Any subsequent lines not including `/()` will also be white.

```
let a = 1;
let b = a/();
let notBlue = b + (1);
let c = (a) / (1);
let d = 1;
let e = 1 / (1);
let f = a + 1 / (a+1) + a;
var g = 1;
```

**Comment by borela** [comment]
This was a typo in the comment pattern near function calls, thank you for spotting this one; Fixed https://github.com/borela/naomi/releases/tag/v4.0.5

**Comment by EmmaSimon** [comment]
Looks good! Thanks a bunch.
