### ISSUE TITLE
Not all ligatures are displayed properly

### ISSUE THREAD

**Issue by orangecoloured** [borela/naomi#159]
I'm using Ubuntu and Fira Code font. You can see the list of ligatures and how they look [here](https://github.com/tonsky/FiraCode/blob/master/showcases/all_ligatures.png). I noticed that !! and && are not being properly formatted. They are displayed as separate characters. Plain text document doesn't have this issue.

```
Minimal code sample used to reproduce the error.

if (!!a && !!b ) {

}
```

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v4.0.8
