### ISSUE TITLE
import type name cannot contain the characters "as"

### ISSUE THREAD

**Issue by ml9951** [borela/naomi#16]
Cannot import any types that contains the characters "as".  The image below should explain it:

![Imgur](http://i.imgur.com/yKvBJ7G.png)

**Comment by borela** [comment]
This was a typo in the syntax due to the recent changes, I sent a [commit](https://github.com/borela/naomi/commit/8230c9e2c7319a20f4be8f24c4fc84e83cedeb3f) to require a space.

**Comment by ml9951** [comment]
Perfect, thanks again!
