### ISSUE TITLE
Nested template literals break highlighting in a big way

### ISSUE THREAD

**Issue by acnebs** [borela/naomi#169]
If you have nested template literals, code highlighting is broken for all subsequent code.
The example below is perfectly valid code and compiles just fine, but breaks syntax highlighting in the rest of the file.

```
const Tab = styled.div`
  color: blue;
`

const Tabs = styled.div`
  ${props => props.vertical && css`
    ${Tab} {
      color: red;
    }
  `}
`
```

Here is a screenshot.

<img width="892" alt="screen shot 2018-08-15 at 11 55 58 am" src="https://user-images.githubusercontent.com/9054108/44145140-4dc9c46c-a082-11e8-9315-ee24afbf8264.png">

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v4.2.1
If the patch didn't work or it still breaks in another case, feel free to reopen or post a new issue;

**Comment by pedroscaff** [comment]
I have a similar issue, the patch works for the case above but when there is a `.` in front of the template literals, it breaks the highlighting.

![image](https://user-images.githubusercontent.com/7076690/48626638-b2eb0f80-e9b2-11e8-9ea0-3b3902d570a2.png)

Removing the `.`

![image](https://user-images.githubusercontent.com/7076690/48626659-c007fe80-e9b2-11e8-9ecc-4f3aca6099e3.png)

Should I open a new issue or is it possible to reopen this issue?

**Comment by borela** [comment]
@pedroscaff Please open a new issue with minimum reproducible sample.
