### ISSUE TITLE
[JS] Line comment stops too early

### ISSUE THREAD

**Issue by StreetStrider** [borela/naomi#177]
Hello. After a couple of releases it seemes that line comment scope breaks to early. I noticed it because I'm using distinctive background for comment.

![line comment](https://user-images.githubusercontent.com/2124761/46911125-49af5100-cf5b-11e8-8e6a-ef37f015bbf8.png)

Expected behavior: comment background should span whole line, because it is a line comment.

**Comment by borela** [comment]
This is probably caused by this line https://github.com/borela/naomi/blob/master/syntaxes/fjsx15/comment/line.sublime-syntax#L34 can you change it to `- match: \n` and see if works? If it does, please send a pull request and I'll merge on all branches.

**Comment by StreetStrider** [comment]
@borela, okay, will do.
Will modifying local files prevent Package Control from taking from upstream?

**Comment by borela** [comment]
In theory no unless a git conflict arises, you'll see package control show an error when it can't pull the origin changes.
