### ISSUE TITLE
toggle_comment doesn't work inside object literal

### ISSUE THREAD

**Issue by YuriGor** [borela/naomi#179]
Try to `ctrl+/` on title or subtitle line
```javascript
const mdf = {
  title: "While your other man was out there,",
  subtitle: "cheatin' and lyin', steppin' all over you"
};
```
Note that native JS syntax works here but incorrectly:
It comments fine, but leaves extra space character before the text,
so please don't repeat its mistake.

**Comment by StreetStrider** [comment]
Bothers me too.

**Comment by StreetStrider** [comment]
To be precise, the issue is not in object literals. I've detected that commenting out stops working when cursor is inside string literlal. fyi @borela

**Comment by borela** [comment]
I sent a patch on the master branch that should fix the empty space artifact, I'll check the string literal issue.

**Comment by borela** [comment]
Released the fix https://github.com/borela/naomi/releases/tag/v4.2.7

**Comment by StreetStrider** [comment]
Confirm it's working ok.
