### ISSUE TITLE
Missing export async function

### ISSUE THREAD

**Issue by clark-pan** [borela/naomi#18]
Screenshot:

<img width="276" alt="screen shot 2017-09-20 at 4 26 51 pm" src="https://user-images.githubusercontent.com/1161431/30634123-9a389838-9e20-11e7-8cf2-9aa1cc55264f.png">

**Comment by borela** [comment]
Nice catch, fixed on version 2.1.1.

**Comment by clark-pan** [comment]
Great. All fixed. Loving the project btw!
