### ISSUE TITLE
dot regex char class scoped as a string

### ISSUE THREAD

**Issue by YuriGor** [borela/naomi#180]
Look at `qq.+` 
dot colored as a string, not as regex selector.

```javascript
var reg = /q[qwerty]\.qq.+s{1,2}\d\s/g;
```

**Comment by borela** [comment]
I could do like the builtin syntax and color it as `constant.other.character-class`, would that be fine? Do you know a better scope for this case?

**Comment by YuriGor** [comment]
i am total noob in the sphere of syntax highlighting and such things,
but may be you need to same scope as used for other selectors like \d \s \W and soon
In native JS/monokai this entries colored with purple color
![image](https://user-images.githubusercontent.com/6861317/46956316-a6b32000-d09d-11e8-9222-716f174b5dce.png)

**Comment by borela** [comment]
I used the same scope as the one being used by the builtin syntax; https://github.com/borela/naomi/releases/tag/v4.2.7

**Comment by YuriGor** [comment]
Tested, works flawlessly.
