### ISSUE TITLE
How to use with LSP?

### ISSUE THREAD

**Issue by spacesuitdiver** [borela/naomi#189]
I'm trying to figure out how to get the "path" to the syntax so LSP knows files I have opened using Naomi syntax should use whatever LSP server. Can anyone help with figuring out what to put in the `syntaxes` array below?

```
        "js": {
            "command": ["lsp-tsserver"],
            "enabled": true,
            "languageId": "javascript",
            "scopes": ["source.js", "source.jsx"],
            "syntaxes": ["Packages/Naomi/syntaxes/naomi.fjsx15.sublime-syntax", "Packages/Babel/JavaScript (Babel).sublime-syntax", "Packages/JavaScript/JavaScript.sublime-syntax"]
        },
```

**Comment by spacesuitdiver** [comment]
Oooh found it out, `Packages/Naomi/syntaxes/naomi.fjsx15.sublime-syntax`, can be found by running `sublime.active_window().active_view().settings().get("syntax")`.

**Comment by borela** [comment]
Which LSP package are you using? Is the auto completition working for javascript?

**Comment by spacesuitdiver** [comment]
@borela tomv564/LSP. Yep!

**Comment by ryanpcmcquen** [comment]
@spacesuitdiver, are you still using this with LSP? I am hitting issues, here is my config:

```
{
	"clients": {
		"lsp-tsserver": {
			"enabled": true,
			"command": ["lsp-tsserver"],
			"languageId": "javascript",
			"scopes": ["source.js", "source.jsx"],
			"syntaxes": ["Packages/Naomi/syntaxes/naomi.fjsx15.sublime-syntax"]
		}
    },
	"complete_all_chars": true
}
```
