### ISSUE TITLE
Missing @include with blocks definitions for SCSS 3 

### ISSUE THREAD

**Issue by clark-pan** [borela/naomi#19]
In SCSS you can define a mixin that takes a block with the `@content;` keyword.

I don't think naomi currently supports this.

<img width="229" alt="screen shot 2017-09-25 at 10 09 48 pm" src="https://user-images.githubusercontent.com/1161431/30813040-e2a6ed96-a23e-11e7-9ff8-0d0e97e882e3.png">

The context thats pushed onto the stack for the sublime syntax changes based on where the include is used. I.e. within a statement it should be that statement context, but within the main file it should the main context (I think? I'm not sure tbh... just a guess)

**Comment by borela** [comment]
Try this branch https://github.com/borela/naomi/tree/hotfix/scss3-fix-content-and-include to see if it fix the issue. Here's the result at my pc:
![fix-content](https://user-images.githubusercontent.com/11317458/30836613-af0dca3a-a235-11e7-8617-2a328675aef3.png)

**Comment by clark-pan** [comment]
Looks good 👍 

I'm sure there are other edge cases that I haven't thought of, but its better than before

**Comment by borela** [comment]
Please let me know if you find more edge cases :grin:
