### ISSUE TITLE
Using 'Function' constructor in an object breaks JS highlighting

### ISSUE THREAD

**Issue by olofssonanton** [borela/naomi#190]
Example:
```
someFunction({
  myString: '',
  myFunctionConstructor: Function
});

const somethingElse = null;
```
![image](https://user-images.githubusercontent.com/6662439/48207372-ca9e1480-e370-11e8-9ba3-624f13b9bbc2.png)

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v4.2.10

**Comment by olofssonanton** [comment]
Solved it, thanks!
