### ISSUE TITLE
[Styled Components & JSPrettier] import error

### ISSUE THREAD

**Issue by mvllow** [borela/naomi#196]
This issue seems to be with Naomi setting a file to CSS in some way that Prettier thinks it is formatting CSS rather than JS. This issue does not happen with babel-sublime. If there is anything I can do to help let me know! Thanks!

Edit: This issue only occurs when saving while your cursor is within styled component code. If you click onto JS code (e.g. the imports) and save, it formats it as JS. Essentially, the issue is that JS is trying to be formatted by JSPrettier as CSS because of how Naomi handles the styled components. Hope this makes sense! This may even be intended behaviour - if so feel free to close this.

Reproduce (this should work with any JS code and JSPrettier installed):
```
import React from 'react'
import styled from 'styled-components'
import { Flex, Box } from 'rebass'
import theme from '../../theme'
```
Console error (minimal):
```
[error] stdin: SyntaxError: (postcss) CssSyntaxError Unknown word (3:10)
[error]   1 | import React from 'react'
[error]   2 | import styled from 'styled-components'
[error] > 3 | import { Flex, Box } from 'rebass'
[error]     |          ^
[error]   4 | import theme from '../../theme'
```

**Comment by coreyward** [comment]
Getting this behavior as well. 

Overall, I'm finding that using Emotion (or other styled components) with Naomi is a rather confusing experience. Part of the time Emmet will work, part of the time it won't. Adding new CSS properties seems to invalidate the syntax of the entire document until the line is finished and valid, and when there's an invalid syntax many other plugins won't work (possible scoping issue?).

**Comment by mvllow** [comment]
Is there any progress on this? Would love to contribute if someone had more information on how to tackle this. Pretty 🆕 to the open source world.

**Comment by acnebs** [comment]
[This pull request for JsPrettier](https://github.com/jonlabelle/SublimeJsPrettier/pull/151/commits/c097fa25280afa963eb9bd7e8921491c3c322e07) seems to indicate that this fix would be as simple as adding somehow setting the file type to `source.css.embedded.js`.

**Comment by mvllow** [comment]
@acnebs I am attempting to learn and figure out where this would need to be added for naomi but am having trouble. If you have any ideas that would be much appreciated! Good find!
