### ISSUE TITLE
Toggle comment unexpectedly uncomments whole block

### ISSUE THREAD

**Issue by ESRogs** [borela/naomi#199]
When multiple lines are commented out, invoking the `naomi_toggle_jsx_comment {"block": false}` command on the last line uncomments all the lines.

I'd expect only the line the cursor is on to be uncommented. That would match the behavior of the regular built in `toggle_comment {"block": false}` command.

```
// console.log('foo');
// console.log('bar');
// console.log('baz');
```

![naomi_toggle_jsx_comment](https://user-images.githubusercontent.com/1746626/51061855-882fc880-15a9-11e9-9f19-6da38c561ce9.gif)

**Comment by StreetStrider** [comment]
#186

**Comment by ESRogs** [comment]
This appears to be a duplicate of the bug @StreetStrider referenced: #186.
