### ISSUE TITLE
Support block level case statements in JS

### ISSUE THREAD

**Issue by clark-pan** [borela/naomi#20]
A little known fact about JS is that `case` statements allow for block level scoping via `{}`. Its getting a bit more use with everyone switching to `const` and `let` instead of `var`, and everyone writing reducers in redux with switch statements.

https://medium.com/@e_himmelfarb/use-curly-braces-with-es6-let-and-const-in-switch-blocks-react-redux-reducers-c0b01b37d748

<img width="258" alt="screen shot 2017-10-04 at 10 13 43 am" src="https://user-images.githubusercontent.com/1161431/31157412-618cbee2-a8ed-11e7-876f-1bc3fb81088c.png">

In my screen shot, the syntax highlighting for the second 'foo' block should match the one outside of the switch statement.

**Comment by borela** [comment]
Try the branch [hotfix/fix-switch-block](https://github.com/borela/naomi/tree/hotfix/fix-switch-block) to see if it fixed the issue.

**Comment by clark-pan** [comment]
LGTM. Thanks @borela :)

I'll come with a PR next time haha, I think I've gotten a handle on the sublime syntax format

**Comment by borela** [comment]
No problem, thank you for finding the bugs :D

**Comment by borela** [comment]
Released the patch https://github.com/borela/naomi/releases/tag/v2.1.3.
