### ISSUE TITLE
Unable to close first html tag

### ISSUE THREAD

**Issue by mvllow** [borela/naomi#213]
I am not able to put a greater-than sign after html tags in js[x] files*. Had this issue and fresh installed sublime on macOS and it went away for a little and then started happening again.

Closing and reopening does not fix. Only plugins are JsPrettier and Naomi. Switched to stock JS syntax and works fine (minus shitty highlighting of course).

```
import React from 'react';

export default () => {
	const x = 0;

	return (
		<div [can't put a greater-than sign here]
	)
}

```

*Pressing the `>` key does nothing

Edit: Console output below

```
Assigning js to syntax Packages/naomi/syntaxes/naomi.fjsx15.sublime-syntax
Packages/naomi/syntaxes/naomi.fjsx15.sublime-syntax: context Packages/Naomi/syntaxes/fjsx15/literal/string/styled-component.sublime-syntax#styled-component-content has a scope name, but is unreachable, so the name will never be used
Packages/naomi/syntaxes/naomi.fjsx15.sublime-syntax: context Packages/Naomi/syntaxes/fjsx15/destructuring/object/property.sublime-syntax#meta-destructuring has a scope name, but is unreachable, so the name will never be used
```

**Comment by mvllow** [comment]
Apologies, looks like this is related to my PR #212. Will submit a patch that seems to fix the first error. The second error is unrelated to the PR.

**Comment by borela** [comment]
No problem, thank you for isolating the issue :D
