### ISSUE TITLE
feature request: Add opaque type

### ISSUE THREAD

**Issue by clark-pan** [borela/naomi#22]
Flow recently added the [opaque type](https://flow.org/en/docs/types/opaque-types/).

I've tried, but I can't seem to figure out where in the syntax to add it... I've only found [1 location](https://github.com/borela/naomi/blob/2c6b358998f4498b66444c16cb18980158955b7c/syntaxes/fjsx15/export.sublime-syntax#L93) but i can't seem to find the main syntax declaration for type.

**Comment by borela** [comment]
I added a couple commits on the master branch to support opaque types, please check if it's working.

**Comment by clark-pan** [comment]
Yep looking good! Thank you.

**Comment by borela** [comment]
Released the fix in v2.6.0.
