### ISSUE TITLE
JS/JSX comment toggle

### ISSUE THREAD

**Issue by kud** [borela/naomi#227]
It does not work here. French azerty keyboard.

Nothing happens on JSX.

**Comment by kud** [comment]
Apparently you should use `forward_slash` instead of `/` to be compliant with all types of i18n keyboards.

**Comment by borela** [comment]
Does it happen everytime or a specific block of code?

**Comment by kud** [comment]
`naomi_toggle_jsx_comment` was never triggered in fact.

I changed my own preferences and now it works:

```
{
    "keys": ["super+shift+:"],
    "command": "naomi_toggle_jsx_comment",
    "args":
    {
      "block": false
    },
    "context": [
    {
      "key": "selector",
      "operator": "equal",
      "operand": "source.js, source.jsx",
      "match_all": true
    }]
  },
  {
    "keys": ["super+shift+alt+:"],
    "command": "naomi_toggle_jsx_comment",
    "args":
    {
      "block": true
    },
    "context": [
    {
      "key": "selector",
      "operator": "equal",
      "operand": "source.js, source.jsx",
      "match_all": true
    }]
  }
```

something weird is that `shift+:` is normally translated via `forward_slash` but it doesn't work.

See the default key binding:

```
	{ "keys": ["super+forward_slash"], "command": "toggle_comment", "args": { "block": false } },
	{ "keys": ["super+alt+forward_slash"], "command": "toggle_comment", "args": { "block": true } },
```

However, you probably should use `forward_slash` to be i18n keyboard compliant but it sounds that it doesn't work so I don't know.

I've got to translate all your key bindings however now, and I don't know how you could fix it to be fair.
