### ISSUE TITLE
Syntax for FJSX15 does not do auto closing tags for jsx

### ISSUE THREAD

**Issue by psyrendust** [borela/naomi#24]
Syntax for FJSX15 does not do auto closing tags for jsx, but it does for HTML 5.

I would expect to get the same type of auto close/auto complete on triggers for jsx files as I would for html files.

![kapture 2017-11-28 at 15 34 00](https://user-images.githubusercontent.com/928502/33350052-c2368cf2-d451-11e7-8d70-307c201f9faa.gif)

**Comment by borela** [comment]
I added a command to the branch [hotfix/close-jsx-tag](https://github.com/borela/naomi/tree/hotfix/close-jsx-tag), can you check if it solved the issue?

**Comment by psyrendust** [comment]
No, that didn't seem to work.

**Comment by borela** [comment]
I believe I finally found the issue, there were scope voids in new line characters, I sent some commits which should fix issue.

Please update and check the branch hotfix/close-jsx-tag again to see if it is working on your machine.

**Comment by psyrendust** [comment]
The change you made in 0d527ee did the trick. I was able to autocomplete html and custom tags when typing `</`.

**Comment by borela** [comment]
Released the patch on the master branch.

**Comment by psyrendust** [comment]
I just wanted to confirm that the public release works. Thanks for your help and quick response!

**Comment by borela** [comment]
Regression, the new syntax system fixed lots of issues, but this behavior is back, I am fixing this as soon as possible as it is affecting my workflow too.

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.0.7
