### ISSUE TITLE
Support TypeScript

### ISSUE THREAD

**Issue by tsujp** [borela/naomi#250]
Is there any word on TypeScript support for Naomi?

**Comment by StreetStrider** [comment]
@tsujp I'm using `JavaScript (Naomi)` on TypeScript and Flow code and it looks acceptable to me. I think Naomi just supports ES extended sytaxes in general, including type annotations as well as `type`/`interface` keyword. Even generics looks well.

**Comment by tsujp** [comment]
I am unsure why this never appeared to work before, I assume I had a rogue setting somewhere. This appears to be working flawlessly now. Yay!
