### ISSUE TITLE
Various syntax bugs

### ISSUE THREAD

**Issue by Thom1729** [borela/naomi#26]
```js
/**/ 42; // Comment doesn't end */

42 /* */ /myVar/g; // Division slashes marked as regexps;

42
/myVar/g; // Division slashes marked as regexps;

myVar
[1]; // Property access marked as array literal.

+function foo() {} []; // Property access marked as array literal.

export default {} []; // Property access marked as array literal.

class Foo {
    bar = 42
    ['prop'] // Property access marked as some kind of flow thing.
}
```

**Comment by borela** [comment]
Hi Thomas
I added a branch to the repo https://github.com/borela/naomi/tree/hotfix/fjsx15-bugs with commits that should fix most of these bugs.

The first one where comments doesn't end, there was a problem in the doc block comments;
The next ones were a little harder specially in the class, it was highlighting the property access as a flow indexer.

I added a condition near variables and literals to expect a property access or an operator to prevent regex literals from consuming the operators. Please check the branch to see if there are any regressions and if it actually fixed the issue.

**Comment by borela** [comment]
I saw your [post on how to deal with expressions](https://github.com/sublimehq/Packages/issues/885), it is a nice solution, I am going to try to implement it into my syntax.

**Comment by borela** [comment]
Released the version 3 which should fix those issues.

**Comment by borela** [comment]
Fixed in the version 3.
