### ISSUE TITLE
shorthand export from support?

### ISSUE THREAD

**Issue by crapthings** [borela/naomi#40]
> export Board from './board'

> export { default as Board } from './board'

https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=true&presets=es2015%2Cstage-0%2Creact&code=export%20v%20from%20%22mod%22%3B%0A

https://babeljs.io/blog/2017/09/12/planning-for-7.0

go to Stage 1: export-default-from

**Comment by borela** [comment]
I pushed a patch on the master branch https://github.com/borela/naomi/commit/3eea1cc61c7c4dff550097caae4375febebdaf73 can you check if it solves the issue?

**Comment by borela** [comment]
Fix https://github.com/borela/naomi/releases/tag/v3.0.6
