### ISSUE TITLE
RegExp in JS

### ISSUE THREAD

**Issue by faiwer** [borela/naomi#51]
![img_18_01_12 34 19_6b135bf6c6b](https://user-images.githubusercontent.com/744114/35083992-ebc2500c-fc4b-11e7-9dfc-8a5610c2e471.png)
```js
const matches = str.match(/^\s*(\{[^}]*\}|[\d.,+*()/\s-]+)\s*/);
```
A little problem at `\s` in `([])`.

**Comment by borela** [comment]
Was this related to the `it` problem? I could not reproduce with that code alone.

**Comment by faiwer** [comment]
Hm. I created a new empty file with only this line:
![img_18_01_16 07 18_ed6fb611ac1](https://user-images.githubusercontent.com/744114/35092462-af892fe8-fc69-11e7-8308-bf5e9ffd9504.png)
```js
const matches = str.match(/^\s*(\{[^}]*\}|[\d.,+*()/\s-]+)\s*/);
```
naomi ends the regExp at `/`, but this `/` in `[]` group :) v3.1.1.

**Comment by borela** [comment]
Which color scheme are you using?

**Comment by borela** [comment]
Ooo I am using sublime's core to highlight the regex, what version of sublime are you using?

**Comment by faiwer** [comment]
- ST: Sublime Text 3, Build 3152
- OS: LinuxMint
- Color schema: CustomHighlightMonokai JSON+ (SL)

I changed for test this color schema by default Monokai, but the problem is still here. Nothing changed. I tried some another schemes - nothing happens.

**Comment by borela** [comment]
It's probably the core, I am using the 3156 build, I'll use the fixed regex code directly from the core to fix the syntax in earlier builds too.

**Comment by borela** [comment]
Check this branch https://github.com/borela/naomi/pull/52 I tested locally and it fixes the issue, had to rewrite the regex patterns to remove the dependency from the core.

**Comment by faiwer** [comment]
![img_18_01_23 29 52_ec4651d97d7](https://user-images.githubusercontent.com/744114/35112195-7fef939c-fca7-11e7-9330-67d2ddfc5aed.png)
So, all right here ;) Thank you. Also I see different colours for different regexp regions. They weren't before.

**Comment by borela** [comment]
I am going to check the scopes before merging.

**Comment by borela** [comment]
It should be close to the colors the scopes the core was giving now. Can you check it before I merge?

**Comment by faiwer** [comment]
naomi:
![img_19_01_00 03 46_d0eee1d2044](https://user-images.githubusercontent.com/744114/35113607-3cc0b588-fcac-11e7-8fff-40e589da5657.png)

default javascript package:
![img_19_01_00 04 09_8166d87c94c](https://user-images.githubusercontent.com/744114/35113625-4a97e65e-fcac-11e7-8902-4f0b7776eaf2.png)

**Comment by borela** [comment]
Which color scheme are you using?
Please post that sample.

**Comment by faiwer** [comment]
sample:
```js
const matches = str.match(/^\s*(\{[^}]*\}|[\d.,+*()/\s-]+)\s*/);
const a = /(19|20)\d\d[- /.](0[1-9]|1[012])[- /.](0[1-9]|[12][0-9]|3[01])/;
const b = /^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]?)$/
```
ColorScheme: Monokai (SL)

**Comment by borela** [comment]
The difference in the const keyword was that in older builds, it was being highlighted as keyword instead of `storage.type`, the newer builds(screen) are have this one corrected; 

The variable name in naomi is scoped as `entity.name.variable`(green) while the core syntax is `variable.other.readwrite` (white), I did that to [follow the guidelines](https://www.sublimetext.com/docs/3/scope_naming.html) and enable the indexer to work with variables, so I think the core is bugged on this one.

The lastest commits I sent to the pull request, made the regex literal similar to how the core is highlighting it(without the bug):

![current](https://user-images.githubusercontent.com/11317458/35114708-cf49b69c-fc6c-11e7-98a1-b45b84e06690.png)

**Comment by borela** [comment]
Released the patch https://github.com/borela/naomi/releases/tag/v3.1.3

**Comment by faiwer** [comment]
> Error loading Packages/JavaScript/Regular Expressions (JavaScript).sublime-syntax: Unable to read Packages/JavaScript/Regular Expressions (JavaScript).sublime-syntax in Packages/Naomi/syntaxes/naomi.fjsx15.sublime-syntax

![img_19_01_00 43 52_c052cb0eb7c](https://user-images.githubusercontent.com/744114/35115283-ddd76a66-fcb1-11e7-868d-c264add65756.png)

Something got wrong. I also tried to remove and install the package again.

**Comment by borela** [comment]
I am going to try to reproduce the on my pc.

**Comment by borela** [comment]
Did try to install from package control or cloned the repo? If you clonned, are you on the master branch?

**Comment by borela** [comment]
I think it's probably a cache issue, sublime compiles the syntaxes to a faster format and put it in a `cache` folder under:

* OS X: `~/Library/Application Support/Sublime Text 3`
* Windows: `%LOCALAPPDATA%\Sublime Text 3`
* Linux: `~/.config/sublime-text-3`

You'll see a `Naomi` directory inside the `cache` directory; Close sublime, delete the Naomi under the cache directory and start it again.

**Comment by faiwer** [comment]
Yeah, you're right. After removing the Cache directory and restarting sublime the problem dissolved.
