### ISSUE TITLE
JSX syntax highlight problem

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#57]
Conditions ruins syntax highlight. May I ask you to fix it?
<img width="956" alt="screen shot 2018-02-05 at 8 40 16 am" src="https://user-images.githubusercontent.com/1213198/35791408-6cd905e8-0a50-11e8-9ece-4bdbf61a39ce.png">

**Comment by max-mykhailenko** [comment]
Hah, sorry, it's not condition. It's a comment inside a brackets

<img width="606" alt="screen shot 2018-02-05 at 8 44 52 am" src="https://user-images.githubusercontent.com/1213198/35791478-d832e4d0-0a50-11e8-92ce-092a24ff1322.png">

**Comment by borela** [comment]
Thank you for isolating the issue, fixed >= [3.3.5](https://github.com/borela/naomi/releases/tag/v3.3.5)

**Comment by max-mykhailenko** [comment]
All looks fine, thanks!
