### ISSUE TITLE
JSX syntax issue

### ISSUE THREAD

**Issue by faiwer** [borela/naomi#58]
Hello. I've encountered with one syntax hightlighting bug. 

![img_06_02_14 56 07_1672189a417](https://user-images.githubusercontent.com/744114/35850088-ea306aa6-0b4d-11e8-8142-c9141b15d868.png)

Minimal code to reproduce the trouble:
![img_06_02_14 56 47_0b85c2cf6e4](https://user-images.githubusercontent.com/744114/35850114-f82406cc-0b4d-11e8-9415-1a0d670e3aba.png)

code:
```jsx
<Aaa>
	<Bbb		
	/>
</Aaa>
```

**Comment by faiwer** [comment]
Hm. This code is influenced too:
![img_06_02_16 45 02_1616bc8e032](https://user-images.githubusercontent.com/744114/35855341-1965729e-0b5d-11e8-9b11-608d3b2c5517.png)

**Comment by borela** [comment]
I tried and code and it is working on my machine on the master branch and the latest version, which version do you have installed?

**Comment by faiwer** [comment]
v3.3.3

**Comment by faiwer** [comment]
After updating to v3.3.5 the problem is end :)
