### ISSUE TITLE
Inline Do in JSX is not parsed

### ISSUE THREAD

**Issue by d3dc** [borela/naomi#61]
I like to use do blocks to avoid hard to read binary operators.

```jsx
<Component>
  { do {
     if (cond) {
       childrenA
     } else {
       childrenB
     }
  }}
</Component>
```

but this doesn't seem to be recognized in `FJSX15+`

---

Something as simple as:
```jsx
  <div>
    <Parsable />
    { do { 1 + 1 }}
  </div>
```
fails

Oddly, if statements are partially recognized.

In this code:
```jsx
<div>
  {do {
    if (condition) {
      1 + 1
    } else {
      2 + 2
    }
  }}
</div>
```
the true branch is parsed.

 
![screen shot 2018-02-07 at 3 20 03 pm](https://user-images.githubusercontent.com/4175887/35944676-7e0aabfc-0c1a-11e8-959a-f7eea92c72b1.png)

**Comment by borela** [comment]
Released the patch https://github.com/borela/naomi/releases/tag/v3.3.6

The {} inside JSX expect expressions and  "Do" expressions were being ignored; I added an exclusive clause to prevent that and now it has the added benefit of distinguishing do expressions from do loops.
