### ISSUE TITLE
Brackets

### ISSUE THREAD

**Issue by faiwer** [borela/naomi#62]
Hello. I've found one bug:
![img_13_02_16 26 42_7961e2c1353](https://user-images.githubusercontent.com/744114/36145160-b0ff983c-10da-11e8-91c0-7f98d78440ab.png)
minimal code to reproduce the bug:
```js
const c = ((a) / 1);
const top = 2;
```
v3.3.6, 3152, LinuxMint

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.3.7 
Feel free to reopen the issue if the patch causes any regression.
