### ISSUE TITLE
Emmet doesn't detect syntax as jsx

### ISSUE THREAD

**Issue by AlexKvazos** [borela/naomi#63]
When using Javascript (Babel), the jsx section has the following scope:

![screen shot 2018-02-14 at 2 27 06 pm](https://user-images.githubusercontent.com/4448627/36226338-279e33fa-1193-11e8-8dcd-93c4673e8fd4.png)

When using FXJS15, the jsx section only has the following scope:

![screen shot 2018-02-14 at 2 27 31 pm](https://user-images.githubusercontent.com/4448627/36226358-377eefee-1193-11e8-9691-3fa7cc35243b.png)

So when doing .myClass[tab] on each of the syntax, yields different results

On FXJS15
![screen shot 2018-02-14 at 2 28 11 pm](https://user-images.githubusercontent.com/4448627/36226379-4d209e60-1193-11e8-9c27-487b25641b3a.png)

On Javascript (Babel)
![screen shot 2018-02-14 at 2 28 40 pm](https://user-images.githubusercontent.com/4448627/36226398-5ef5cd72-1193-11e8-9333-4be73f2569c4.png)

**Comment by borela** [comment]
This is something I did to enhance the support for color schemes and make JSX be highlighted similar to HTML because most color schemes dont have direct support for JSX; I did raised an issue https://github.com/sergeche/emmet-sublime/issues/680 and the change would be minimal, but it looks like Emmet is not being maintaned :/

I'll check again if adding `source.jsx` would break too many color schemes.

**Comment by AlexKvazos** [comment]
Normally people using Jsx know they have to use a maintained color scheme. Personally I use monokai pro and it works wonders.

Can it be configurable?

________________________________

**Comment by borela** [comment]
> Normally people using JSX know they have to use a maintained color scheme. 

That's an extremely good point and I think it's enough reason to change the root to `source.jsx.jsx1` (the repeated suffix is to know from which script the scope is being generated, makes it easier to track bugs).

**Comment by borela** [comment]
I sent the patch to the master branch, can you check if it is working?

**Comment by AlexKvazos** [comment]
My js files now have no syntax highlighting

**Comment by AlexKvazos** [comment]
Never mind, it works!! Thanks for quick fix.
