### ISSUE TITLE
JS Problem with passing  function in object

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#66]
Function in `render` key has incorrect highlight.

Problem:
<img width="617" alt="screen shot 2018-02-19 at 3 47 30 pm" src="https://user-images.githubusercontent.com/1213198/36380829-5fa84630-158c-11e8-946a-5e512862505f.png">

But this one works fine
<img width="604" alt="screen shot 2018-02-19 at 3 47 46 pm" src="https://user-images.githubusercontent.com/1213198/36380828-5f8fa3aa-158c-11e8-938d-f5280ec0c2c1.png">

**Comment by borela** [comment]
Released the patch https://github.com/borela/naomi/releases/tag/v3.4.4

**Comment by eballeste** [comment]
Hi guys! Off topic but what theme are you guys using?

**Comment by borela** [comment]
The patch worked, the bug was fixed :D

**Comment by max-mykhailenko** [comment]
🥇
