### ISSUE TITLE
[JS] typeof broke inside if conditional

### ISSUE THREAD

**Issue by Whoaa512** [borela/naomi#68]
Broken: 
![screenshot 2018-02-20 15 25 40](https://user-images.githubusercontent.com/1581943/36454794-3940012e-1652-11e8-8c78-df491d6595b1.png)

Repro case:

```js

class Button extends PureComponent {
    onClick = (e) => {
        const { dispatch, disabled } = this.props

        if (disabled) {
            return
        }

        if (typeof dispatch === 'function') {
            dispatch(trackLinkClick({ type: LINKCLICK }))
        }
    }
}
```

**Comment by borela** [comment]
Released the [patch](https://github.com/borela/naomi/releases/tag/v3.4.5), thank you for isolating the issue, it was lot easier to pin point the error :D

**Comment by Whoaa512** [comment]
Thanks!

**Comment by Whoaa512** [comment]
Will that also fix `!`,`~`, `+`, and other symbols in if conditionals?

**Comment by Whoaa512** [comment]
![screenshot 2018-02-20 16 02 45](https://user-images.githubusercontent.com/1581943/36455953-64f27414-1657-11e8-888f-bb9df69f018a.png)


```js
+fooo
!fooo
~fooo
if (+fooo) {}
if (!fooo) {}
if (~fooo) {}
```

**Comment by borela** [comment]
Yes :D I was surprised this bug didn't bit me the last days.

![image](https://user-images.githubusercontent.com/11317458/36456158-4bbaf7ca-1682-11e8-8dd9-b3c4d6df7ffe.png)

**Comment by Whoaa512** [comment]
Awesome!
