### ISSUE TITLE
JS Broken highlight 

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#69]
Last closed tag broken and all after it too. I tried to remove all inside condition, but it didn't help
<img width="374" alt="screen shot 2018-02-21 at 10 42 50 am" src="https://user-images.githubusercontent.com/1213198/36470617-22a34ece-16f4-11e8-8f70-0b20c91d0df2.png">

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.4.7

**Comment by max-mykhailenko** [comment]
When I will be able to update sublime? Package control didn't see 3.4.7, only 3.4.6.

**Comment by borela** [comment]
Package control usually updates the repo every 2 ~ 3 hours, unfortunately that's not controlled by me.

**Comment by max-mykhailenko** [comment]
I completely understand, thanks.

**Comment by max-mykhailenko** [comment]
Fixed 👍
