### ISSUE TITLE
Javascript - destructuring/spread assignment breaks syntax highlighting

### ISSUE THREAD

**Issue by BruOp** [borela/naomi#70]
Here's a screenshot:
![brokensyntax](https://user-images.githubusercontent.com/11671506/36490613-a015623c-16f6-11e8-996c-4738f02e34d3.png)

Here's the repro code:
```
class SomeComponent extends Component {

  componentDidMount = () => {
    const { match: { params: { stepIndex }}, currentStep } = this.props;
  }

  render() {
    return null;
  }
}

function mapStateToProps(state) {
  return {};
}

export default withRouter(connect(mapStateToProps)(SomeComponent));
```

It works better if the spread assignment doesn't go more than one level deep:
![notsobroken](https://user-images.githubusercontent.com/11671506/36490551-7f3a3362-16f6-11e8-8a9e-2c262c63bfd2.png)

```
class SomeComponent extends Component {

  componentDidMount = () => {
    const { match } = this.props;
  }

  render() {
    return null;
  }
}

function mapStateToProps(state) {
  return {};
}

export default withRouter(connect(mapStateToProps)(SomeComponent));
```

**Comment by borela** [comment]
Thank you for isolating the issue :D Fixed: https://github.com/borela/naomi/releases/tag/v3.5.0

**Comment by BruOp** [comment]
Wow that was fast! Thanks a lot, and thanks for this package, it's great!

PS How long until that release gets pushed to Sublime's package control?

**Comment by borela** [comment]
I am glad it is being useful :D Package control usually update it every 2~3 hours, right now it is showing the latest version, restart sublime and it might update the package;

**Comment by BruOp** [comment]
Awesome thanks! Looks like it's working now :+1:
