### ISSUE TITLE
js objects with dynamic values ignored

### ISSUE THREAD

**Issue by eballeste** [borela/naomi#71]
Thank you for Naomi, it has helped me find bad javascript syntax within my code which I have corrected as I notice them.

I encountered one issue however and am not sure if what I'm doing is bad code or something that is not being picked up by Naomi since it gets interpreted correctly. I believe the issue seems to be with me trying to dynamically determine the values of the object's properties within the initialization of the object itself:
![screen shot 2018-02-21 at 3 17 48 pm](https://user-images.githubusercontent.com/6924108/36503423-13d78cda-171b-11e8-9b15-e734083a9e1f.png)

**Comment by borela** [comment]
It looks like a bug in the syntax itself, I'll try to isolate the bug.

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.5.1
