### ISSUE TITLE
Cast object literal keys as strings or numbers for syntax highlighting

### ISSUE THREAD

**Issue by neaumusic** [borela/naomi#72]
Similar to Babel plugin, Object keys should be strings or numbers!!

Desired (Babel) syntax highlight:
![Desired (Babel) syntax highlight](https://imgur.com/WD9KUiN.jpg)

Current (Naomi) syntax highlight:
![Current (Naomi) syntax highlight](https://imgur.com/99VGx3W.jpg)

**Comment by neaumusic** [comment]
I was getting a weird error "Expected element key" when trying to add that snippet to the Monokai.tmTheme file, but I ended up adding those scopes in the String entry and it works great

![object literal string syntax highlighting](https://imgur.com/fR3skdK.jpg)

```
<dict>
  <key>name</key>
  <string>String</string>
  <key>scope</key>
  <string>string, meta.object-literal.key, meta.object-literal.key variable.other.readwrite</string>
  <key>settings</key>
  <dict>
    <key>foreground</key>
    <string>#E6DB74</string>
  </dict>
</dict>
```

**Comment by borela** [comment]
https://github.com/borela/naomi/releases/tag/v3.7.0 
Reverted object keys to unquoted strings except for numbers.

**Comment by borela** [comment]
The latest patch was published and now the syntax will adopt babel sublime's behavior highlighting object literal keys.

**Comment by A-312** [comment]
If someone want to revert this change:

`Sublime Text 3/Packages/User/Monokai.sublime-color-scheme`:
```
{
    "rules": [
        {
            "scope": "source.js meta.declaration.variable.js.fjsx15 meta.object-literal.js.fjsx15 meta.block.js.fjsx15 meta.object-literal.key.js.fjsx15 string.unquoted.js.fjsx15",
            "foreground": "var(white)"
        },
    ]
}
```
