### ISSUE TITLE
jsx conditional rendering bug

### ISSUE THREAD

**Issue by eballeste** [borela/naomi#73]
getting distinct differences with the attributes of a jsx element when placing markup within curly braces for conditional rendering, not sure which of the two versions is correctly highlighted

![screen shot 2018-02-21 at 6 32 01 pm](https://user-images.githubusercontent.com/6924108/36511677-94d1fa90-1735-11e8-813f-840de212fbe7.png)

**Comment by borela** [comment]
I tried typing the code section in the print and couldn't reproduce the error, can you create a minimal code sample that triggers the problem?

Off topic: Are the Fade and Swipe components open source?

**Comment by eballeste** [comment]
this:
```javascript
import React, { Component } from 'react';

export default class Test extends Component {
  constructor(props) {
    super(props);
  }

  render() {
    const { prop } = this.props;

    return(
      <div>
        <div className="test" randomProp={true} prop={prop}>
          <p>Hi!</p>
        </div>
        {true &&
          <div className="test" randomProp={false}>
            <p>Hi! Hi!</p>
          </div>
        }
      </div>
    );
  }
}
```
is seen as this:
<img width="429" alt="screen shot 2018-02-21 at 8 28 35 pm" src="https://user-images.githubusercontent.com/6924108/36515110-d9d27bf0-1745-11e8-9ab6-4a84ed7ab552.png">

could it be an issue with my [theme](https://github.com/equinusocio/material-theme)?

the Fade component is just a simple component i made that uses css transitions on opacity to hide it's children based on the prop i give it

[Slide](https://github.com/lyfeyaj/swipe/tree/master/examples/react) is open source and works well with react.

**Comment by borela** [comment]
It looks different on my machine but I am not sure if I fixed it by accident because I just finished the patch that fixes the other issue you posted :s

![image](https://user-images.githubusercontent.com/11317458/36515851-1d405880-175a-11e8-958e-8fe481e3b59b.png)

With the cursor over a character on `className` and on `randomProp`, press Ctrl+Shift+Alt+P and show me what you see, mine is:

## className
```
source.jsx
meta.tag.other.html.jsx.jsx1
meta.attribute-with-value.html.jsx.jsx1
entity.other.attribute-name.class.html.jsx.jsx1
```

## randomProp
```
source.jsx
meta.tag.other.html.jsx.jsx1
meta.attribute-with-value.html.jsx.jsx1
entity.other.attribute-name.html.jsx.jsx1
```

So considering the color scheme, className having a different color is expected because it is considered a "core" attribute (className, key...), but randomProp should be purple like in my screenshot.

**Comment by borela** [comment]
I believe the shortcut to show the scopes on mac is ⌃ + ⇧ + P

**Comment by eballeste** [comment]
weird, i get the same thing that you posted, 

i changed the color scheme and it seems to be something that only happens with the material themes

**Comment by borela** [comment]
What are the scopes for randomProp(the yellow one) at the second tag?

**Comment by eballeste** [comment]
the same as yours

just got the latest version, i think you did accidentally fix it, working now!!
<img width="343" alt="screen shot 2018-02-21 at 10 35 37 pm" src="https://user-images.githubusercontent.com/6924108/36519116-a36a5cba-1757-11e8-8ba0-e7dc38b26076.png">

**Comment by eballeste** [comment]
very awesome! thank you for the explanation in the color difference between the core attributes and props and for getting this sorted so fast!

**Comment by borela** [comment]
You are welcome :D This is the first time I fix something by accident lol
