### ISSUE TITLE
destructuring an object within an array method

### ISSUE THREAD

**Issue by eballeste** [borela/naomi#74]
```javascript
const { stuff } = {stuff: true};

[{stuff: true}, {stuff: false}].forEach(item => {
  const { stuff } = item;
});
```

looks like this:
<img width="338" alt="screen shot 2018-02-21 at 11 57 06 pm" src="https://user-images.githubusercontent.com/6924108/36521296-20472608-1764-11e8-845a-295dc00e8871.png">

first `stuff` variable:
```
source.js 
meta.declaration.variable.js.fjsx15 
meta.binding.destructuring.mapping.js.fjsx15 
meta.block.js.fjsx15 
entity.name.variable.js.fjsx15
```
second one:
```
source.js 
meta.function-call.js.fjsx15 
meta.group.js.fjsx15 
meta.function.js.fjsx15 
meta.block.js.fjsx15 
meta.declaration.variable.js.fjsx15 
meta.binding.destructuring.mapping.js.fjsx15 
meta.block.js.fjsx15 
entity.name.variable.js.fjsx15
```

**Comment by borela** [comment]
The scopes looks correct but it is strange that material color scheme is acting this way, I'll take a look at it.

**Comment by eballeste** [comment]
this one i checked with several themes and it happens it most, not all of them

**Comment by borela** [comment]
Found the issue, the color schemes  don't have a rule for `entity.name.variable`.

Variables are using 2 scopes:
* `entity.name.variable` when a variable is declared;
* `variable.other.readwrite`  for any other uses;

I was using this distinction to enable the indexer to pick variables without showing duplicates in the list; I'll do some tests if reverting it to just variable will cause any issues.

**Comment by borela** [comment]
Updated the variables' scopes to use `variable.other.readwrite` and it caused no issues; https://github.com/borela/naomi/releases/tag/v3.6.0

It'll probably solve this issue.

**Comment by eballeste** [comment]
works! awesome!
