### ISSUE TITLE
shorthand properties in objects

### ISSUE THREAD

**Issue by eballeste** [borela/naomi#75]
sorry for opening so many issues, not expecting such a fast turnaround on these things so thank you very much for responding to all of them! 

I found another weird bug when assigning shorthand properties to new objects within array methods:
```javascript
const hello = true;
const newObj = {stuff: true, hello};

[{stuff: true}, {stuff: false}].forEach(item => {
  const hello = true;
  const { stuff } = item;

  return { newStuff: stuff, hello};
});
```
is seen as: 
![screen shot 2018-02-22 at 4 41 18 pm](https://user-images.githubusercontent.com/6924108/36565753-6f90578a-17ef-11e8-993a-ca85951679cd.png)

first `hello` shorthand property:
```
source.js 
meta.declaration.variable.js.fjsx15 
meta.object-literal.js.fjsx15 
meta.block.js.fjsx15
```

second `hello` shorthand property:
```
source.js 
meta.function-call.js.fjsx15 
meta.group.js.fjsx15 
meta.function.js.fjsx15 
meta.block.js.fjsx15 
meta.object-literal.js.fjsx15 
meta.block.js.fjsx15
```

**Comment by borela** [comment]
> sorry for opening so many issues

Don't worry, I like the fact you are reporting them, those bugs affects me too and sometimes is hard to create a minimal sample to track them :D

**Comment by borela** [comment]
Found the issue :D Fixed Fixed https://github.com/borela/naomi/releases/tag/v3.6.3
