### ISSUE TITLE
[JS] import * as Foo from 'foo' broken

### ISSUE THREAD

**Issue by Whoaa512** [borela/naomi#76]
![screenshot 2018-02-22 17 30 00](https://user-images.githubusercontent.com/1581943/36573527-5196cd52-17f6-11e8-83e7-7dc57c16ffe3.png)

```javascript
import * as Foo from 'dsakkd'
```

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.6.3
