### ISSUE TITLE
JSX: Closing tag breaks syntax highlighting

### ISSUE THREAD

**Issue by octet-stream** [borela/naomi#77]
Hello!
Too sad to see that babel-sublime have no maintenance for a while. So, I just wanted to say thank you for this package at first. :)
But seems like I found a little bug in highlighting:

![image](https://user-images.githubusercontent.com/7884558/36614787-e3a7518c-18ee-11e8-998b-c1cf09d543c6.png)

As you can see, the syntax highlighting breaks right after closing tag. It also affects `class` components:

![image](https://user-images.githubusercontent.com/7884558/36614875-2e11ca40-18ef-11e8-88c9-8bc82d041f36.png)

And I don't think it depends on theme or a color scheme, because I've tested it in some of then.
Buy the way, as I can see, the problem appears when I'm using `class` keyword in a property name. When I'm removing it – everything looks just fine.

**Comment by borela** [comment]
It's bug, it is trying to highlight a class declaration after `props.`. I'll work on the patch :D

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.6.4 Package control crawler seams to be down, to receive the latest patch you'll have to clone the repo or wait for package control to update.

**Comment by octet-stream** [comment]
Okay then. I'll wait for package control updates. Thanks for the fast feedback and fix 👍 
I'm closing this issue for now.
