### ISSUE TITLE
Compability with DocBlockr

### ISSUE THREAD

**Issue by AlexKvazos** [borela/naomi#78]
Looks like DocBlockr is not catching this as a Javascript context. Not sure if this is related to this package however with babel-sublime there was no issue.

https://github.com/spadgos/sublime-jsdocs

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.6.4 Package control crawler seams to be down, to receive the latest patch you'll have to clone the repo or wait for package control to update.

**Comment by borela** [comment]
By the way, thanks for the heads up about the DocBlockr plugin, I loved it :D

**Comment by borela** [comment]
I've been using DocBlockr for a while and I can confirm that this issue was fixed.

**Comment by AlexKvazos** [comment]
Thanks Borela!! Really happy with the support  you are giving to your
package!

On Sun, Feb 25, 2018 at 11:38 AM, Alexandre Borela <notifications@github.com
