### ISSUE TITLE
JS: Static Array properties breaks highlighting (partially)

### ISSUE THREAD

**Issue by octet-stream** [borela/naomi#79]
Hi again. One more little possible bug in your package:
![image](https://user-images.githubusercontent.com/7884558/36643790-6bd78284-1a61-11e8-8439-ffa9876873e0.png)

Static properties of Array, such as `Array.from` and `Array.isArray` are breaking (partially) highlighting from the next line.

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.6.5 I also fixed a similar bug for Node and React globals.

**Comment by octet-stream** [comment]
Thanks!
