### ISSUE TITLE
Variables with "get" in their names

### ISSUE THREAD

**Issue by faiwer** [borela/naomi#80]
Hello. I found a small bug.

![img_25_02_22 47 23_a8002a0ec7a](https://user-images.githubusercontent.com/744114/36644003-dd56cdf4-1a7d-11e8-9e12-97fcb2887076.png)

code:
```js
const target = `any`;
const a = { target };
```

I think naomi thinks that `get` in `target` is a getter ;)
v3.6.1

**Comment by borela** [comment]
This was fixed in the latest versions (>= 3.6.4) :D I had to rewrite the object literal keys.

![image](https://user-images.githubusercontent.com/11317458/36644150-c07bddb2-1a34-11e8-9289-2a157f157f6a.png)

Unless there's some code before it causing the issue.

**Comment by faiwer** [comment]
I've checked it. Yep. It's working. Thank you ;)
