### ISSUE TITLE
JS Broken Highlight

### ISSUE THREAD

**Issue by max-mykhailenko** [borela/naomi#82]
v.3.6.4

<img width="788" alt="screen shot 2018-02-25 at 9 51 41 pm" src="https://user-images.githubusercontent.com/1213198/36645756-2e5f1f42-1a76-11e8-9979-17aa4f5beac4.png">

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.6.6

**Comment by max-mykhailenko** [comment]
Ok,  thanks!
