### ISSUE TITLE
eqDiv and sub-properties

### ISSUE THREAD

**Issue by faiwer** [borela/naomi#84]
Hello. It's again me ;)
![img_26_02_18 43 43_61431b14fcb](https://user-images.githubusercontent.com/744114/36671203-0bb80c92-1b25-11e8-9a91-e885c55af5f7.png)
I put above the image, but something has got wrong in github, and I don't see the image. You can open it: http://ftp.faiwer.ru/img_26_02_18%3A43%3A43_61431b14fcb.png

```js
a.b /= 10;
```

This bug occurs only with `/=` operator. All another operators (`*=`, `-=`, `+=`) work properly. Also it occurs only if I use a subproperty of object.

**Comment by faiwer** [comment]
Hm. It also works with `/` operator:

![img_26_02_18 49 56_820115084e9](https://user-images.githubusercontent.com/744114/36671468-db944282-1b25-11e8-972b-800ea1fda38d.png)

v3.6.4

**Comment by borela** [comment]
This was fixed on >= 3.6.5 but package control crawler is not working properly https://github.com/wbond/package_control/issues/1337 :c

To receive the update you would have to clone the repo or apply the patch manually https://github.com/borela/naomi/compare/v3.6.4...v3.6.6

**Comment by borela** [comment]
I'll leave this open to alert other users.

**Comment by borela** [comment]
Package control is working again and got the latest patches which should solve this issue.
