### ISSUE TITLE
Incorrect string syntax detection

### ISSUE THREAD

**Issue by neaumusic** [borela/naomi#85]
Notice that the mathematical operation `/` and after is highlighted as a string.
By removing `'string'` from the dict scope, the issue goes away, which indicates that `'string'` is being determined incorrectly

![Incorrect String Syntax](https://imgur.com/LrU6uTv.jpg)

**Comment by borela** [comment]
This was fixed on the master branch tag >= 3.6.5 but package control is having issues updating the packages:

https://forum.sublimetext.com/t/announcement-package-control-degraded-functionality/35381/2

**Comment by borela** [comment]
Package control is working again and got the latest patches which should solve this issue.
