### ISSUE TITLE
FJSX15 arrow function return type highlighting

### ISSUE THREAD

**Issue by grit96** [borela/naomi#88]
There seems to be a bug with the syntax highlighting when I have an arrow function with a flow return type. The highlighting breaks when the return type is an array of something `MyType[]`. My workarounds currently are using the function keyword rather than an arrow function, or to use the `Array<MyType>` syntax.

![image](https://user-images.githubusercontent.com/3957608/36839158-19b295fe-1d39-11e8-9eef-a3d4a7897cc9.png)

![image](https://user-images.githubusercontent.com/3957608/36839171-23e9704c-1d39-11e8-97f9-f1cd3005165b.png)

![image](https://user-images.githubusercontent.com/3957608/36839137-0d374338-1d39-11e8-96e2-1f3131b694b4.png)

It affects highlighting for the rest of the file:

![image](https://user-images.githubusercontent.com/3957608/36839198-3e4721f0-1d39-11e8-864b-47e54b77e3a0.png)

**Comment by borela** [comment]
Fixed https://github.com/borela/naomi/releases/tag/v3.7.2

**Comment by grit96** [comment]
Thanks for the quick fix!
