### ISSUE TITLE
JS: A batch of highlighting issues

### ISSUE THREAD

**Issue by octet-stream** [borela/naomi#89]
Hi again :)
I found more highlighting issues in your package in 7.1.0 version :D
1. Highlighting breaks after `module.default` property:
![image](https://user-images.githubusercontent.com/7884558/36860862-83da4152-1d93-11e8-9650-065a3d7f0a97.png)
I think, you just need to ignore highlighting of any keyword after accessor operator :)

2. The second issue appears with `yield` keyword, when I'm using it in assignment or return expressions:
![image](https://user-images.githubusercontent.com/7884558/36861315-9803ec18-1d94-11e8-83ac-15862451efc7.png)

3. Just a possible issue, `async` keyword highlights differently then `function` (even in your Candyman color scheme):
![image](https://user-images.githubusercontent.com/7884558/36861878-4f81dd18-1d96-11e8-996f-92cd4d5aefeb.png)

And could you please to add `.mjs` extension support to your package? Node.js will use it to handle [ES modules](https://nodejs.org/api/esm.html).

**Comment by borela** [comment]
Thank you for isolating the bugs :D the async scope was indeed wrong. I released the patches https://github.com/borela/naomi/releases/tag/v3.7.3

**Comment by octet-stream** [comment]
Too strange, but I don't see any changes, related to this issue and release note in comparing between to latest releases: https://github.com/borela/naomi/compare/v3.7.2...v3.7.3

**Comment by borela** [comment]
My bad, remote was out of sync so the push failed and I didn't see it https://github.com/borela/naomi/compare/v3.7.2...v3.7.4

**Comment by octet-stream** [comment]
Thank you 👍
