### ISSUE TITLE
Naomi breaks vue syntax highlighting

### ISSUE THREAD

**Issue by ellipticaldoor** [borela/naomi#90]
![image](https://user-images.githubusercontent.com/3449006/36933642-a621eeee-1ed4-11e8-8307-c28007866cd4.png)

To reproduce this behaviour first you have to install the package Vue Syntax Highlight.

After installing Naomi and restarting sublime text, vue components start to look like in the screenshot above.

These errors are easy to see when using the official vue template https://github.com/vuejs-templates/webpack

**Comment by borela** [comment]
I'll see what I can patch on this package enhance support.

**Comment by ellipticaldoor** [comment]
Cool :)

**Comment by borela** [comment]
After looking at the Vue syntax, it seams that a new version is already being developed on the branch `new`,  that version solves the incompatibilities that you saw but it requires sublime's dev build to use it.
