### ISSUE TITLE
Emmet . className # id jsx keybindings

### ISSUE THREAD

**Issue by franciscolourenco** [borela/naomi#93]
```js
    {
        "keys": [
            "."
        ],
        "args": {
            "attribute": "className"
        },
        "command": "emmet_insert_attribute",
        "context": [
            {
                "operand": "source.jsx meta.naomi meta.tag.other.html.jsx.jsx1",
                "operator": "equal",
                "match_all": true,
                "key": "selector"
            },
            {
                "operator": "equal",
                "operand": true,
                "key": "setting.auto_id_class"
            }
        ]
    },
    {
        "keys": [
            "#"
        ],
        "args": {
            "attribute": "id"
        },
        "command": "emmet_insert_attribute",
        "context": [
            {
                "operand": "source.jsx meta.naomi meta.tag.other.html.jsx.jsx1",
                "operator": "equal",
                "match_all": true,
                "key": "selector"
            },
            {
                "operator": "equal",
                "operand": true,
                "key": "setting.auto_id_class"
            }
        ]
    }
```

**Comment by borela** [comment]
What does these shortcuts do? I tried using it and it didn't do anything even when I changed my emmet settings.

**Comment by franciscolourenco** [comment]
It adds `className=""` when you press `.` and `id=""` when you press `#`.

![emmet](https://user-images.githubusercontent.com/208149/37208966-b0841078-23a3-11e8-896d-40c49c75d798.gif)

The scope might need to tweaking to restrict in only the the html attributes.

**Comment by borela** [comment]
Nice, I'll do some tests with different scopes.

**Comment by borela** [comment]
I had to add a meta scope to JSX {} expressions and prevent the auto complete to kick in there.

**Comment by borela** [comment]
Added the . and # shortcuts
https://github.com/borela/naomi/blob/master/Default.sublime-keymap#L229
https://github.com/borela/naomi/blob/master/Default.sublime-keymap#L246

This will definitely improve my workflow.

**Comment by franciscolourenco** [comment]
Looking forward for the next release

**Comment by borela** [comment]
Released https://github.com/borela/naomi/releases/tag/v3.11.0
