### ISSUE TITLE
[JS] Nested destructuring 

### ISSUE THREAD

**Issue by Whoaa512** [borela/naomi#98]
Not sure if this is an actual problem. Looks like the destructured property (`me`) is getting colored as a function.

## Image
<img width="407" alt="screenshot 2018-03-16 17 27 32" src="https://user-images.githubusercontent.com/1581943/37549637-55b949a0-293f-11e8-9b8b-36f3882d8b8b.png">

## Code Sample

```javascript
Promise.resolve()
    .then(response => {
        const { me: { id, email } } = response

        raven.setUserContext({ email, id })
        return response
    })
    .catch(() => null)

```

**Comment by borela** [comment]
The `me` is being marked as:

```
source.js
meta.naomi
meta.function-call.js.fjsx15
meta.group.js.fjsx15
meta.function.js.fjsx15
meta.block.js.fjsx15
meta.declaration.variable.js.fjsx15
meta.binding.destructuring.mapping.js.fjsx15
meta.block.js.fjsx15
meta.binding.destructuring.mapping.key.js.fjsx15
```

Technically is not wrong but normally color schemes don't target meta scopes so I would probably need a specific scope there. I'll check what other apps are doing in this case.

**Comment by borela** [comment]
Most apps don't specify a scope there which makes it look inconsistent on most color schemes;

A solution I'll implement is to make it similar to object literals, it looks like you are using oceanic next, so it would like:

![image](https://user-images.githubusercontent.com/11317458/37550059-12e70bb8-2966-11e8-8738-4543035aafc3.png)

**Comment by borela** [comment]
The patch is on the master branch, you can clone the repo if you want to use it right now, I'll wait until I finish cleaning up the comment toggle plugin before I publish the next version.

**Comment by borela** [comment]
Fixed in https://github.com/borela/naomi/releases/tag/v3.12.3

**Comment by Whoaa512** [comment]
Thank you!
