### ISSUE TITLE
Create New Objects with Template Tags

### ISSUE THREAD

**Issue by StabbarN** [borela/naomi#99]
## Image
<img width="754" alt="template tag" src="https://user-images.githubusercontent.com/921390/37553794-ebd891d6-29ce-11e8-83c6-30bbf1799bc1.png">

Something goes wrong when Naomi parses a temlate tag inside curly brackets, that is
```
someKey: myTag`${someVar}`,
```
turns all code after it to an incorrect color (in my case, with my theme, green).

## Code sample
```
function myTag(strings, ...substitutions) {
  return 'something'
}

const someVar = 1

const l1 = {
  someKey: `${someVar}`, // This is ok
}

const dummy = myTag`${someVar}` // This is also ok

const l2 = {
  someKey: myTag`${someVar}`, // Can't have template tags inside object (curly brackets)
}
const everythingBelowAreGreen = 0
```

**Comment by 2Pacalypse-** [comment]
I have a similar problem which I think is probably related (if it's not I'll create a new issue). The same effect happens if you have curly brackets inside a template tag, but only if it's also inside regular parenthesis as well.

For example, this:
```js
const MyDiv = styled(Div)`
  margin: 0px;
  padding-right: 8px;
  line-height: calc(${standardIncrement} - ${barHeight});
  vertical-align: middle;
`
```
Results in:

![naomi](https://user-images.githubusercontent.com/4757944/37555012-430b14ee-29e1-11e8-8261-9648fcac57a6.png)

**Comment by borela** [comment]
Both issues were related but in different parts of the syntax;
Fixed in https://github.com/borela/naomi/releases/tag/v3.12.3

![image](https://user-images.githubusercontent.com/11317458/37555280-dcf77048-29c3-11e8-9414-ffd8fdd2faf2.png)

**Comment by 2Pacalypse-** [comment]
Awesome, great work!

**Comment by borela** [comment]
Thank you both for isolating the issue, having the sample codes made it a lot easier to track the correct context.

**Comment by StabbarN** [comment]
Thank you! That was quickly corrected!
